# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/qt_design/addTale_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(609, 854)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(200, 40, 231, 31))
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 35, 141, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 121, 31))
        self.label_4.setObjectName("label_4")
        self.select_picture = QtWidgets.QPushButton(Form)
        self.select_picture.setGeometry(QtCore.QRect(40, 380, 111, 31))
        self.select_picture.setObjectName("select_picture")
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(200, 370, 261, 181))
        self.image.setObjectName("image")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 100, 131, 31))
        self.label.setObjectName("label")
        self.author = QtWidgets.QLineEdit(Form)
        self.author.setGeometry(QtCore.QRect(200, 100, 231, 31))
        self.author.setObjectName("author")
        self.ok_btn = QtWidgets.QPushButton(Form)
        self.ok_btn.setGeometry(QtCore.QRect(390, 810, 75, 23))
        self.ok_btn.setObjectName("ok_btn")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(470, 810, 75, 23))
        self.cancel.setObjectName("cancel")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 580, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 630, 141, 91))
        self.label_5.setObjectName("label_5")
        self.description = QtWidgets.QTextEdit(Form)
        self.description.setGeometry(QtCore.QRect(200, 160, 231, 181))
        self.description.setObjectName("description")
        self.characters = QtWidgets.QTextEdit(Form)
        self.characters.setGeometry(QtCore.QRect(210, 590, 241, 111))
        self.characters.setObjectName("characters")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "НАЗВАНИЕ"))
        self.label_4.setText(_translate("Form", "ОПИСАНИЕ"))
        self.select_picture.setText(_translate("Form", "Выбрать картинку"))
        self.image.setText(_translate("Form", "IMAGE"))
        self.label.setText(_translate("Form", "АВТОР"))
        self.ok_btn.setText(_translate("Form", "OK"))
        self.cancel.setText(_translate("Form", "Cancel"))
        self.label_2.setText(_translate("Form", "ГЛАВНЫЕ ГЕРОИ"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-style:italic;\">Для четкого отображения </span></p><p><span style=\" font-style:italic;\">героев в таблице пиште</span></p><p><span style=\" font-style:italic;\"> их имена через запятую</span></p></body></html>"))
