# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/qt_design/moreInfo_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(428, 686)
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(30, 20, 371, 41))
        self.title.setObjectName("title")
        self.author = QtWidgets.QLabel(Form)
        self.author.setGeometry(QtCore.QRect(30, 70, 171, 21))
        self.author.setObjectName("author")
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(30, 380, 371, 211))
        self.image.setObjectName("image")
        self.text_description = QtWidgets.QTextBrowser(Form)
        self.text_description.setEnabled(True)
        self.text_description.setGeometry(QtCore.QRect(30, 250, 361, 131))
        self.text_description.setObjectName("text_description")
        self.characters = QtWidgets.QTextBrowser(Form)
        self.characters.setGeometry(QtCore.QRect(30, 140, 361, 101))
        self.characters.setObjectName("characters")
        self.delete_btn = QtWidgets.QPushButton(Form)
        self.delete_btn.setGeometry(QtCore.QRect(30, 650, 75, 23))
        self.delete_btn.setObjectName("delete_btn")
        f = open('data/style/style.css', 'r')
        self.style = f.read()
        f.close()
        Form.setStyleSheet(self.style)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "Title"))
        self.author.setText(_translate("Form", "author"))
        self.delete_btn.setText(_translate("Form", "УДАЛИТЬ"))
